version: '3.5'

networks:
  port-authority-proxy:
    external: true

services:

  ohscribe:
    build: .
    container_name: "ohscribe"
    ports:
      - 5000:5000
    command: ./boot.sh
    volumes:
      - ./app:/app
      - ./data:/tmp/ohscribe/data
    networks:
      - port-authority-proxy
    environment:
      - UPLOAD_FOLDER=${OHSCRIBE_UPLOAD_FOLDER}
      - SECRET_KEY=${OHSCRIBE_SECRET_KEY}
    labels:
      traefik.backend: ohscribe
      traefik.port: 5000
      traefik.frontend.rule: Host:${PROJECT_FULL_URL}
      traefik.docker.network: port-authority-proxy
