version: '3.5'

networks:
  port-ability-proxy:
    external: true

services:

  ohscribe:
    build: .
    container_name: "ohscribe_ohscribe"
    ports:
      - 5000:5000
    command: ./boot.sh
    volumes:
      - ./app:/app
      - ./data:/tmp/ohscribe/data
    networks:
      - port-ability-proxy
    environment:
      - UPLOAD_FOLDER=${OHSCRIBE_UPLOAD_FOLDER}
      - SECRET_KEY=${OHSCRIBE_SECRET_KEY}
      - HOST_ADDR=${OHSCRIBE_HOST_ADDR}
      - LOG_VERBOSITY=${LOG_VERBOSITY}
      - ADMIN_PASSWORD=${OHSCRIBE_ADMIN_PASSWORD}
    labels:
      traefik.backend: ohscribe
      traefik.port: 5000
      traefik.frontend.rule: Host:${PROJECT_FULL_URL}
      traefik.docker.network: port-ability-proxy
